### ISSUE TITLE
Use ArgoCD sync policy `ServerSideApply=true` for CRDs

### ISSUE THREAD

**Issue by simu** [projectsyn/component-prometheus#59]
## Context

We've updated the component to use ArgoCD sync policy `Replace=true` for the CRDs in #58 to workaround #57. This unblocks us short-term. However, ArgoCD v2.5 will have support for server-side apply with sync policy `ServerSideApply=true` and we should switch to that to ensure that CRDs are never deleted and recreated during sync (this shouldn't happen at the moment either unless "Force" is selected during a manual sync).

## Alternatives

Keep sync policy `Replace=true`.

**Comment by corvus-ch** [comment]
Instead of fixing this for just one component, we will do so by changing the default of ArgoCD. The internal issue to track this progress is SYN-1873.
